; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Tue Sep 08 2020 09:53:12 GMT-0500 (Central Daylight Time)

