; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Tue Sep 08 2020 09:53:13 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P0
T0