; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Oct 05 2020 21:46:10 GMT-0500 (Central Daylight Time)
G91               ; relative positioning
G1 H2 Z5 F1000    ; lift Z relative to current position
G1 H1 Z-450 F1000 ; move quickly to Z axis endstop and stop there (first pass)
G1 H2 Z5 F600     ; go back a few mm
G1 H1 Z-450 F360  ; move slowly to Z axis endstop and stop there (second pass)
G90                ; absolute positioning

