; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Oct 05 2020 21:46:12 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P0

