; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.2 on Fri Jan 22 2021 14:58:46 GMT-0600 (Central Standard Time)
M280 P64 S10 ; deploy BLTouch

